language: python
python:
  - "3.4"
  - "2.7"
env:
  - REQ="Django>=1.8,<1.9"
  - REQ="Django>=1.9,<1.10"
  - REQ="Django>=1.10,<1.11"
  - REQ="Django>=1.11,<2.0"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $REQ towel flake8
  - python setup.py install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp && cd .. && flake8 ."
